# Generated by Django 4.0.1 on 2022-01-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAPtask', '0003_alter_user_fist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
