# Generated by Django 4.0.1 on 2022-01-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAPtask', '0004_remove_user_email_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fist_name',
            field=models.CharField(max_length=128, unique=True, verbose_name="Ім'я"),
        ),
    ]
